<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFanesxc\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFanesxc/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFanesxc.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFanesxc\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \ContainerFanesxc\EccubeDevDebugProjectContainer([
    'container.build_hash' => 'Fanesxc',
    'container.build_id' => 'f3eb72bc',
    'container.build_time' => 1729704780,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFanesxc');
