<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'eccube.purchase.flow.shopping.holder_preprocessors' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Collection.php';
include_once $this->targetDirs[3].'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php';

$a = ${($_ = isset($this->services['Eccube\\Service\\PurchaseFlow\\Processor\\TaxProcessor']) ? $this->services['Eccube\\Service\\PurchaseFlow\\Processor\\TaxProcessor'] : $this->load('getTaxProcessorService.php')) && false ?: '_'};

return $this->services['eccube.purchase.flow.shopping.holder_preprocessors'] = new \Doctrine\Common\Collections\ArrayCollection([0 => $a, 1 => ${($_ = isset($this->services['Eccube\\Service\\PurchaseFlow\\Processor\\OrderNoProcessor']) ? $this->services['Eccube\\Service\\PurchaseFlow\\Processor\\OrderNoProcessor'] : $this->load('getOrderNoProcessorService.php')) && false ?: '_'}, 2 => $a]);
