<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'eccube.purchase.flow.cart' shared service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/PurchaseFlow.php';
include_once $this->targetDirs[3].'/app/Customize/Service/PurchaseFlow/PurchaseFlow.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ValidatorTrait.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemValidator.php';
include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Service/PurchaseFlow/Processor/QuantityAdjustValidator.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemHolderPreprocessor.php';
include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Service/PurchaseFlow/Processor/DeliveryFeeFreeForProductOptionPreprocessor.php';
include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Service/PurchaseFlow/Processor/QuantityUpdatePreprocessor.php';
include_once $this->targetDirs[3].'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Collection.php';
include_once $this->targetDirs[3].'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php';

$this->services['eccube.purchase.flow.cart'] = $instance = new \Customize\Service\PurchaseFlow\PurchaseFlow();

$a = ${($_ = isset($this->services['Customize\\Service\\OrderHelper']) ? $this->services['Customize\\Service\\OrderHelper'] : $this->load('getOrderHelperService.php')) && false ?: '_'};
$b = ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'};

$instance->setFlowType('cart');
$instance->setItemValidators(${($_ = isset($this->services['eccube.purchase.flow.cart.item_validators']) ? $this->services['eccube.purchase.flow.cart.item_validators'] : $this->load('getEccube_Purchase_Flow_Cart_ItemValidatorsService.php')) && false ?: '_'});
$instance->setItemHolderValidators(${($_ = isset($this->services['eccube.purchase.flow.cart.holder_validators']) ? $this->services['eccube.purchase.flow.cart.holder_validators'] : $this->load('getEccube_Purchase_Flow_Cart_HolderValidatorsService.php')) && false ?: '_'});
$instance->setItemPreprocessors(${($_ = isset($this->services['eccube.purchase.flow.cart.item_preprocessors']) ? $this->services['eccube.purchase.flow.cart.item_preprocessors'] : ($this->services['eccube.purchase.flow.cart.item_preprocessors'] = new \Doctrine\Common\Collections\ArrayCollection())) && false ?: '_'});
$instance->setItemHolderPreprocessors(${($_ = isset($this->services['eccube.purchase.flow.cart.holder_preprocessors']) ? $this->services['eccube.purchase.flow.cart.holder_preprocessors'] : ($this->services['eccube.purchase.flow.cart.holder_preprocessors'] = new \Doctrine\Common\Collections\ArrayCollection())) && false ?: '_'});
$instance->setItemHolderPostValidators(${($_ = isset($this->services['eccube.purchase.flow.cart.holder_post_validators']) ? $this->services['eccube.purchase.flow.cart.holder_post_validators'] : $this->load('getEccube_Purchase_Flow_Cart_HolderPostValidatorsService.php')) && false ?: '_'});
$instance->addItemPreprocessor(${($_ = isset($this->services['Plugin\\ProductOption\\Service\\PurchaseFlow\\Processor\\OptionPreprocessor']) ? $this->services['Plugin\\ProductOption\\Service\\PurchaseFlow\\Processor\\OptionPreprocessor'] : $this->load('getOptionPreprocessorService.php')) && false ?: '_'});
$instance->addItemValidator(new \Plugin\ProductOption\Service\PurchaseFlow\Processor\QuantityAdjustValidator($a, $b));
$instance->addItemValidator(${($_ = isset($this->services['Plugin\\ProductOption\\Service\\PurchaseFlow\\Processor\\SaleLimitValidator']) ? $this->services['Plugin\\ProductOption\\Service\\PurchaseFlow\\Processor\\SaleLimitValidator'] : $this->load('getSaleLimitValidatorService.php')) && false ?: '_'});
$instance->addItemValidator(${($_ = isset($this->services['Plugin\\ProductOption\\Service\\PurchaseFlow\\Processor\\StockValidator']) ? $this->services['Plugin\\ProductOption\\Service\\PurchaseFlow\\Processor\\StockValidator'] : $this->load('getStockValidatorService.php')) && false ?: '_'});
$instance->addItemHolderPreprocessor(new \Plugin\ProductOption\Service\PurchaseFlow\Processor\DeliveryFeeFreeForProductOptionPreprocessor(${($_ = isset($this->services['Plugin\\ProductOption\\Repository\\OptionRepository']) ? $this->services['Plugin\\ProductOption\\Repository\\OptionRepository'] : $this->load('getOptionRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ProductOption\\Repository\\OptionCategoryRepository']) ? $this->services['Plugin\\ProductOption\\Repository\\OptionCategoryRepository'] : $this->load('getOptionCategoryRepositoryService.php')) && false ?: '_'}));
$instance->addItemHolderPreprocessor(new \Plugin\ProductOption\Service\PurchaseFlow\Processor\QuantityUpdatePreprocessor(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, $a, $b));

return $instance;
