<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Service\PurchaseFlow\Processor\HdnWariItemProcessor' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemPreprocessor.php';
include_once $this->targetDirs[3].'/app/Customize/Service/PurchaseFlow/Processor/HdnWariItemProcessor.php';

return $this->services['Customize\\Service\\PurchaseFlow\\Processor\\HdnWariItemProcessor'] = new \Customize\Service\PurchaseFlow\Processor\HdnWariItemProcessor();
