<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ProductOption\Form\Extension\Admin\OrderItemExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Form/Extension/Admin/OrderItemExtension.php';

return $this->services['Plugin\\ProductOption\\Form\\Extension\\Admin\\OrderItemExtension'] = new \Plugin\ProductOption\Form\Extension\Admin\OrderItemExtension(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\TaxRuleService']) ? $this->services['Eccube\\Service\\TaxRuleService'] : $this->getTaxRuleServiceService()) && false ?: '_'});
