<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.z.3mx.4' shared service.

return $this->services['service_locator.z.3mx.4'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['extension' => function () {
    $f = function (\Eccube\Twig\Extension\EccubeExtension $v = null) { return $v; }; return $f(${($_ = isset($this->services['Eccube\\Twig\\Extension\\EccubeExtension']) ? $this->services['Eccube\\Twig\\Extension\\EccubeExtension'] : $this->getEccubeExtensionService()) && false ?: '_'});
}]);
