<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Form\Extension\Admin\SearchOrderTypeExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Customize/Form/Extension/Admin/SearchOrderTypeExtension.php';

return $this->services['Customize\\Form\\Extension\\Admin\\SearchOrderTypeExtension'] = new \Customize\Form\Extension\Admin\SearchOrderTypeExtension(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Customize\\Repository\\CategoryRepository']) ? $this->services['Customize\\Repository\\CategoryRepository'] : $this->load('getCategoryRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Customize\\Repository\\HdnTenpoRepository']) ? $this->services['Customize\\Repository\\HdnTenpoRepository'] : $this->load('getHdnTenpoRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Customize\\Repository\\Master\\BumonRepository']) ? $this->services['Customize\\Repository\\Master\\BumonRepository'] : $this->load('getBumonRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\PaymentRepository']) ? $this->services['Eccube\\Repository\\PaymentRepository'] : $this->load('getPaymentRepositoryService.php')) && false ?: '_'});
