<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL5usogg\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL5usogg/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerL5usogg.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerL5usogg\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \ContainerL5usogg\EccubeDevDebugProjectContainer([
    'container.build_hash' => 'L5usogg',
    'container.build_id' => 'fa7c5eba',
    'container.build_time' => 1729700950,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL5usogg');
