<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Repository\Master\BumonRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Customize/Repository/Master/BumonRepository.php';

return $this->services['Customize\\Repository\\Master\\BumonRepository'] = new \Customize\Repository\Master\BumonRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
