<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ProductOption\Repository\CartItemOptionCategoryRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Repository/CartItemOptionCategoryRepository.php';

return $this->services['Plugin\\ProductOption\\Repository\\CartItemOptionCategoryRepository'] = new \Plugin\ProductOption\Repository\CartItemOptionCategoryRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
