<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Form\Extension\Admin\CategoryTypeExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Customize/Form/Extension/Admin/CategoryTypeExtension.php';

return $this->services['Customize\\Form\\Extension\\Admin\\CategoryTypeExtension'] = new \Customize\Form\Extension\Admin\CategoryTypeExtension(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Customize\\Repository\\HdnTenpoRepository']) ? $this->services['Customize\\Repository\\HdnTenpoRepository'] : $this->load('getHdnTenpoRepositoryService.php')) && false ?: '_'});
