<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Service\PurchaseFlow\PurchaseFlow' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/PurchaseFlow.php';
include_once $this->targetDirs[3].'/app/Customize/Service/PurchaseFlow/PurchaseFlow.php';

return $this->services['Customize\\Service\\PurchaseFlow\\PurchaseFlow'] = new \Customize\Service\PurchaseFlow\PurchaseFlow();
