<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ProductOption\Form\Extension\ShippingMultipleExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Form/Extension/ShippingMultipleExtension.php';

return $this->services['Plugin\\ProductOption\\Form\\Extension\\ShippingMultipleExtension'] = new \Plugin\ProductOption\Form\Extension\ShippingMultipleExtension(${($_ = isset($this->services['Eccube\\Repository\\ShippingRepository']) ? $this->services['Eccube\\Repository\\ShippingRepository'] : $this->load('getShippingRepositoryService.php')) && false ?: '_'});
