<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.4_o4l3m' shared service.

return $this->services['service_locator.4_o4l3m'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['tokenManager' => function () {
    return ${($_ = isset($this->services['security.csrf.token_manager']) ? $this->services['security.csrf.token_manager'] : $this->getSecurity_Csrf_TokenManagerService()) && false ?: '_'};
}]);
