<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ProductOption\Form\Extension\AddCartExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Form/Extension/AddCartExtension.php';

return $this->services['Plugin\\ProductOption\\Form\\Extension\\AddCartExtension'] = new \Plugin\ProductOption\Form\Extension\AddCartExtension(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ProductOption\\Repository\\OptionCategoryRepository']) ? $this->services['Plugin\\ProductOption\\Repository\\OptionCategoryRepository'] : $this->load('getOptionCategoryRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\\ProductOption\\Repository\\ProductOptionRepository']) ? $this->services['Plugin\\ProductOption\\Repository\\ProductOptionRepository'] : $this->load('getProductOptionRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\TaxRuleService']) ? $this->services['Eccube\\Service\\TaxRuleService'] : $this->getTaxRuleServiceService()) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'});
