<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ProductOption\Repository\OrderItemOptionRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Repository/OrderItemOptionRepository.php';

return $this->services['Plugin\\ProductOption\\Repository\\OrderItemOptionRepository'] = new \Plugin\ProductOption\Repository\OrderItemOptionRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
