<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'productoption.api.allow_list' shared service.

return $this->services['productoption.api.allow_list'] = new \ArrayObject(['Eccube\\Entity\\Product' => [0 => 'ProductOptions'], 'Plugin\\ProductOption\\Entity\\ProductOption' => [0 => 'sort_no', 1 => 'Option'], 'Plugin\\ProductOption\\Entity\\Option' => [0 => 'id', 1 => 'name', 2 => 'backend_name', 3 => 'description', 4 => 'type', 5 => 'is_required', 6 => 'require_min', 7 => 'require_max', 8 => 'sort_no', 9 => 'OptionCategories'], 'Plugin\\ProductOption\\Entity\\OptionCategory' => [0 => 'id', 1 => 'name', 2 => 'description', 3 => 'disable_flg', 4 => 'init_flg', 5 => 'value', 6 => 'delivery_free_flg', 7 => 'multiple_flg', 8 => 'sort_no'], 'Eccube\\Entity\\OrderItem' => [0 => 'option_price', 1 => 'option_tax', 2 => 'OrderItemOptions'], 'Plugin\\ProductOption\\Entity\\OrderItemOption' => [0 => 'label', 1 => 'sort_no', 2 => 'OrderItemOptionCategories'], 'Plugin\\ProductOption\\Entity\\OrderItemOptionCategory' => [0 => 'price', 1 => 'tax', 2 => 'value', 3 => 'delivery_free_flg', 4 => 'sort_no', 5 => 'option_category_id']]);
