<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBkqr004\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBkqr004/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBkqr004.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerBkqr004\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerBkqr004\EccubeProdProjectContainer([
    'container.build_hash' => 'Bkqr004',
    'container.build_id' => '5b10852e',
    'container.build_time' => 1730355428,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBkqr004');
