<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Service\PurchaseFlow\Processor\HdnWariOrderProcessor' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ValidatorTrait.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemHolderValidator.php';
include_once $this->targetDirs[3].'/app/Customize/Service/PurchaseFlow/Processor/HdnWariOrderProcessor.php';

return $this->services['Customize\\Service\\PurchaseFlow\\Processor\\HdnWariOrderProcessor'] = new \Customize\Service\PurchaseFlow\Processor\HdnWariOrderProcessor(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'});
