<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Form\Type\HdnSelectSaijiBlockType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Customize/Form/Type/HdnSelectSaijiBlockType.php';

return $this->services['Customize\\Form\\Type\\HdnSelectSaijiBlockType'] = new \Customize\Form\Type\HdnSelectSaijiBlockType(${($_ = isset($this->services['Customize\\Repository\\CategoryRepository']) ? $this->services['Customize\\Repository\\CategoryRepository'] : $this->load('getCategoryRepositoryService.php')) && false ?: '_'});
