<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Form\Type\HdnSelectTenpoBlockType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Customize/Form/Type/HdnSelectTenpoBlockType.php';

return $this->services['Customize\\Form\\Type\\HdnSelectTenpoBlockType'] = new \Customize\Form\Type\HdnSelectTenpoBlockType(${($_ = isset($this->services['Customize\\Repository\\HdnTenpoRepository']) ? $this->services['Customize\\Repository\\HdnTenpoRepository'] : $this->load('getHdnTenpoRepositoryService.php')) && false ?: '_'});
