<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Repository\HdnSaijiTenpoRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Customize/Repository/HdnSaijiTenpoRepository.php';

return $this->services['Customize\\Repository\\HdnSaijiTenpoRepository'] = new \Customize\Repository\HdnSaijiTenpoRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
