<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Customize\Form\Extension\NonMemberTypeExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Customize/Form/Extension/NonMemberTypeExtension.php';

return $this->services['Customize\\Form\\Extension\\NonMemberTypeExtension'] = new \Customize\Form\Extension\NonMemberTypeExtension(${($_ = isset($this->services['Customize\\Repository\\RecieveRepository']) ? $this->services['Customize\\Repository\\RecieveRepository'] : $this->load('getRecieveRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Customize\\Repository\\CategoryRepository']) ? $this->services['Customize\\Repository\\CategoryRepository'] : $this->load('getCategoryRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\DeliveryRepository']) ? $this->services['Eccube\\Repository\\DeliveryRepository'] : $this->load('getDeliveryRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Customize\\Repository\\HdnTenpoRepository']) ? $this->services['Customize\\Repository\\HdnTenpoRepository'] : $this->load('getHdnTenpoRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Customize\\Repository\\VisitRepository']) ? $this->services['Customize\\Repository\\VisitRepository'] : $this->load('getVisitRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Customize\\Repository\\TenposRepository']) ? $this->services['Customize\\Repository\\TenposRepository'] : $this->load('getTenposRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Customize\\Repository\\HprefRepository']) ? $this->services['Customize\\Repository\\HprefRepository'] : $this->load('getHprefRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'});
