<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ProductOption\Service\PurchaseFlow\Processor\OptionPreprocessor' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemPreprocessor.php';
include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Service/PurchaseFlow/Processor/OptionPreprocessor.php';

return $this->services['Plugin\\ProductOption\\Service\\PurchaseFlow\\Processor\\OptionPreprocessor'] = new \Plugin\ProductOption\Service\PurchaseFlow\Processor\OptionPreprocessor(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\CartService']) ? $this->services['Eccube\\Service\\CartService'] : $this->getCartServiceService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Service\\TaxRuleService']) ? $this->services['Eccube\\Service\\TaxRuleService'] : $this->getTaxRuleServiceService()) && false ?: '_'});
