<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ProductOption\Form\Type\Admin\ProductOptionType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Form/Type/Admin/ProductOptionType.php';

return $this->services['Plugin\\ProductOption\\Form\\Type\\Admin\\ProductOptionType'] = new \Plugin\ProductOption\Form\Type\Admin\ProductOptionType();
