<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.vrjib1m' shared service.

return $this->services['service_locator.vrjib1m'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['orderPdfService' => function () {
    $f = function (\Plugin\ProductOption\Service\ProductOptionOrderPdfService $v = null) { return $v; }; return $f(${($_ = isset($this->services['Plugin\\ProductOption\\Service\\ProductOptionOrderPdfService']) ? $this->services['Plugin\\ProductOption\\Service\\ProductOptionOrderPdfService'] : $this->load('getProductOptionOrderPdfServiceService.php')) && false ?: '_'});
}]);
