<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ProductOption\Form\Extension\ShippingMultipleItemExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Form/Extension/ShippingMultipleItemExtension.php';

return $this->services['Plugin\\ProductOption\\Form\\Extension\\ShippingMultipleItemExtension'] = new \Plugin\ProductOption\Form\Extension\ShippingMultipleItemExtension();
