<?php

namespace Proxies\__CG__\Plugin\ProductOption\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Option extends \Plugin\ProductOption\Entity\Option implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'id', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'name', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'backend_name', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'description', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'type', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'pricedisp_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'description_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'is_required', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'require_min', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'require_max', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'sort_no', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'create_date', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'update_date', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'OptionCategories', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'Creator', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'optionCategories', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'defaultCategorys', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'disableCategory'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'id', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'name', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'backend_name', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'description', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'type', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'pricedisp_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'description_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'is_required', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'require_min', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'require_max', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'sort_no', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'create_date', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'update_date', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'OptionCategories', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'Creator', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'optionCategories', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'defaultCategorys', '' . "\0" . 'Plugin\\ProductOption\\Entity\\Option' . "\0" . 'disableCategory'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Option $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultCategory', []);

        return parent::getDefaultCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisableCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisableCategory', []);

        return parent::getDisableCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBackendName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackendName', [$name]);

        return parent::setBackendName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getBackendName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackendName', []);

        return parent::getBackendName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$date]);

        return parent::setCreateDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', [$date]);

        return parent::setUpdateDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', []);

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSortNo($sortNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSortNo', [$sortNo]);

        return parent::setSortNo($sortNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSortNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortNo', []);

        return parent::getSortNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionFlg($flg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionFlg', [$flg]);

        return parent::setDescriptionFlg($flg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionFlg', []);

        return parent::getDescriptionFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricedispFlg($flg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricedispFlg', [$flg]);

        return parent::setPricedispFlg($flg);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricedispFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricedispFlg', []);

        return parent::getPricedispFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRequired($flg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRequired', [$flg]);

        return parent::setIsRequired($flg);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRequired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRequired', []);

        return parent::getIsRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequireMin($min)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequireMin', [$min]);

        return parent::setRequireMin($min);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequireMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequireMin', []);

        return parent::getRequireMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequireMax($max)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequireMax', [$max]);

        return parent::setRequireMax($max);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequireMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequireMax', []);

        return parent::getRequireMax();
    }

    /**
     * {@inheritDoc}
     */
    public function addOptionCategory(\Plugin\ProductOption\Entity\OptionCategory $optionCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOptionCategory', [$optionCategory]);

        return parent::addOptionCategory($optionCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOptionCategory(\Plugin\ProductOption\Entity\OptionCategory $optionCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOptionCategory', [$optionCategory]);

        return parent::removeOptionCategory($optionCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionCategories', []);

        return parent::getOptionCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\Eccube\Entity\Member $creator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', [$creator]);

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', []);

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function offsetExists($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetExists', [$offset]);

        return parent::offsetExists($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetSet($offset, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetSet', [$offset, $value]);

        return parent::offsetSet($offset, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetGet($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetGet', [$offset]);

        return parent::offsetGet($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetUnset($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetUnset', [$offset]);

        return parent::offsetUnset($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertiesFromArray(array $arrProps, array $excludeAttribute = array (
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertiesFromArray', [$arrProps, $excludeAttribute, $parentClass]);

        return parent::setPropertiesFromArray($arrProps, $excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$excludeAttribute, $parentClass]);

        return parent::toArray($excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toNormalizedArray(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toNormalizedArray', [$excludeAttribute]);

        return parent::toNormalizedArray($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toJSON(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJSON', [$excludeAttribute]);

        return parent::toJSON($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toXML(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toXML', [$excludeAttribute]);

        return parent::toXML($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function copyProperties($srcObject, array $excludeAttribute = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyProperties', [$srcObject, $excludeAttribute]);

        return parent::copyProperties($srcObject, $excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnotationReader(\Doctrine\Common\Annotations\Reader $Reader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnotationReader', [$Reader]);

        return parent::setAnnotationReader($Reader);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnotationReader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnotationReader', []);

        return parent::getAnnotationReader();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityIdentifierAsArray(\Eccube\Entity\AbstractEntity $Entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityIdentifierAsArray', [$Entity]);

        return parent::getEntityIdentifierAsArray($Entity);
    }

}
