<?php

namespace Proxies\__CG__\Plugin\ProductOption\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderItemOption extends \Plugin\ProductOption\Entity\OrderItemOption implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . '_calc', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'option_price', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'option_tax', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'delivery_free_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'arrOrderItemOptionCategory', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'id', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'label', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'sort_no', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'option_id', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'OrderItem', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'OrderItemOptionCategories'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . '_calc', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'option_price', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'option_tax', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'delivery_free_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'arrOrderItemOptionCategory', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'id', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'label', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'sort_no', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'option_id', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'OrderItem', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OrderItemOption' . "\0" . 'OrderItemOptionCategories'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrderItemOption $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function _calc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_calc', []);

        return parent::_calc();
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionPrice', []);

        return parent::getOptionPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionTax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionTax', []);

        return parent::getOptionTax();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryFreeFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryFreeFlg', []);

        return parent::getDeliveryFreeFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrOrderItemOptionCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrOrderItemOptionCategory', []);

        return parent::getArrOrderItemOptionCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setSortNo($sortNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSortNo', [$sortNo]);

        return parent::setSortNo($sortNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSortNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortNo', []);

        return parent::getSortNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptionId($optionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptionId', [$optionId]);

        return parent::setOptionId($optionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionId', []);

        return parent::getOptionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderItem($orderItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderItem', [$orderItem]);

        return parent::setOrderItem($orderItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderItem', []);

        return parent::getOrderItem();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderItemOptionCategory(\Plugin\ProductOption\Entity\OrderItemOptionCategory $orderItemOptionCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderItemOptionCategory', [$orderItemOptionCategory]);

        return parent::addOrderItemOptionCategory($orderItemOptionCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderItemOptionCategory(\Plugin\ProductOption\Entity\OrderItemOptionCategory $orderItemOptionCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderItemOptionCategory', [$orderItemOptionCategory]);

        return parent::removeOrderItemOptionCategory($orderItemOptionCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderItemOptionCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderItemOptionCategories', []);

        return parent::getOrderItemOptionCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function offsetExists($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetExists', [$offset]);

        return parent::offsetExists($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetSet($offset, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetSet', [$offset, $value]);

        return parent::offsetSet($offset, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetGet($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetGet', [$offset]);

        return parent::offsetGet($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetUnset($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetUnset', [$offset]);

        return parent::offsetUnset($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertiesFromArray(array $arrProps, array $excludeAttribute = array (
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertiesFromArray', [$arrProps, $excludeAttribute, $parentClass]);

        return parent::setPropertiesFromArray($arrProps, $excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$excludeAttribute, $parentClass]);

        return parent::toArray($excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toNormalizedArray(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toNormalizedArray', [$excludeAttribute]);

        return parent::toNormalizedArray($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toJSON(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJSON', [$excludeAttribute]);

        return parent::toJSON($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toXML(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toXML', [$excludeAttribute]);

        return parent::toXML($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function copyProperties($srcObject, array $excludeAttribute = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyProperties', [$srcObject, $excludeAttribute]);

        return parent::copyProperties($srcObject, $excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnotationReader(\Doctrine\Common\Annotations\Reader $Reader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnotationReader', [$Reader]);

        return parent::setAnnotationReader($Reader);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnotationReader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnotationReader', []);

        return parent::getAnnotationReader();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityIdentifierAsArray(\Eccube\Entity\AbstractEntity $Entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityIdentifierAsArray', [$Entity]);

        return parent::getEntityIdentifierAsArray($Entity);
    }

}
