<?php

namespace Proxies\__CG__\Plugin\ProductOption\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OptionCategory extends \Plugin\ProductOption\Entity\OptionCategory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'label', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'id', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'name', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'description', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'disable_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'init_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'value', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'delivery_free_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'multiple_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'sort_no', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'create_date', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'update_date', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'Option', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'OptionImages', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'Creator'];
        }

        return ['__isInitialized__', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'label', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'id', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'name', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'description', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'disable_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'init_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'value', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'delivery_free_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'multiple_flg', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'sort_no', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'create_date', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'update_date', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'Option', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'OptionImages', '' . "\0" . 'Plugin\\ProductOption\\Entity\\OptionCategory' . "\0" . 'Creator'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OptionCategory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$date]);

        return parent::setCreateDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', [$date]);

        return parent::setUpdateDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', []);

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSortNo($sortNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSortNo', [$sortNo]);

        return parent::setSortNo($sortNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSortNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortNo', []);

        return parent::getSortNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisableFlg($flg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisableFlg', [$flg]);

        return parent::setDisableFlg($flg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisableFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisableFlg', []);

        return parent::getDisableFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitFlg($flg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitFlg', [$flg]);

        return parent::setInitFlg($flg);
    }

    /**
     * {@inheritDoc}
     */
    public function getInitFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitFlg', []);

        return parent::getInitFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function setValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValue', [$value]);

        return parent::setValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', []);

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryFreeFlg($flg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryFreeFlg', [$flg]);

        return parent::setDeliveryFreeFlg($flg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryFreeFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryFreeFlg', []);

        return parent::getDeliveryFreeFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function setMultipleFlg($flg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMultipleFlg', [$flg]);

        return parent::setMultipleFlg($flg);
    }

    /**
     * {@inheritDoc}
     */
    public function getMultipleFlg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMultipleFlg', []);

        return parent::getMultipleFlg();
    }

    /**
     * {@inheritDoc}
     */
    public function setOption(\Plugin\ProductOption\Entity\Option $Option)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOption', [$Option]);

        return parent::setOption($Option);
    }

    /**
     * {@inheritDoc}
     */
    public function getOption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOption', []);

        return parent::getOption();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\Eccube\Entity\Member $creator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', [$creator]);

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function addOptionImage(\Plugin\ProductOption\Entity\OptionImage $optionImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOptionImage', [$optionImage]);

        return parent::addOptionImage($optionImage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOptionImage(\Plugin\ProductOption\Entity\OptionImage $optionImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOptionImage', [$optionImage]);

        return parent::removeOptionImage($optionImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionImages', []);

        return parent::getOptionImages();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', []);

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function offsetExists($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetExists', [$offset]);

        return parent::offsetExists($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetSet($offset, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetSet', [$offset, $value]);

        return parent::offsetSet($offset, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetGet($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetGet', [$offset]);

        return parent::offsetGet($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetUnset($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetUnset', [$offset]);

        return parent::offsetUnset($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertiesFromArray(array $arrProps, array $excludeAttribute = array (
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertiesFromArray', [$arrProps, $excludeAttribute, $parentClass]);

        return parent::setPropertiesFromArray($arrProps, $excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
), \ReflectionClass $parentClass = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$excludeAttribute, $parentClass]);

        return parent::toArray($excludeAttribute, $parentClass);
    }

    /**
     * {@inheritDoc}
     */
    public function toNormalizedArray(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toNormalizedArray', [$excludeAttribute]);

        return parent::toNormalizedArray($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toJSON(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJSON', [$excludeAttribute]);

        return parent::toJSON($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function toXML(array $excludeAttribute = array (
  0 => '__initializer__',
  1 => '__cloner__',
  2 => '__isInitialized__',
  3 => 'AnnotationReader',
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toXML', [$excludeAttribute]);

        return parent::toXML($excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function copyProperties($srcObject, array $excludeAttribute = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'copyProperties', [$srcObject, $excludeAttribute]);

        return parent::copyProperties($srcObject, $excludeAttribute);
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnotationReader(\Doctrine\Common\Annotations\Reader $Reader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnotationReader', [$Reader]);

        return parent::setAnnotationReader($Reader);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnotationReader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnotationReader', []);

        return parent::getAnnotationReader();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityIdentifierAsArray(\Eccube\Entity\AbstractEntity $Entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityIdentifierAsArray', [$Entity]);

        return parent::getEntityIdentifierAsArray($Entity);
    }

}
