<?php

namespace Proxies\__CG__\Customize\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HdnTenpo extends \Customize\Entity\HdnTenpo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'id', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'tenpo_cd', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'tenpo_name', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'tenpo_ryaku_name', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'sort_no', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'visible', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'phone_number', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'uke_tenpo', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'SaijiTenpos'];
        }

        return ['__isInitialized__', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'id', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'tenpo_cd', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'tenpo_name', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'tenpo_ryaku_name', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'sort_no', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'visible', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'phone_number', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'uke_tenpo', '' . "\0" . 'Customize\\Entity\\HdnTenpo' . "\0" . 'SaijiTenpos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HdnTenpo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTenpoCd(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTenpoCd', []);

        return parent::getTenpoCd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTenpoCd(string $tenpo_cd): \Customize\Entity\HdnTenpo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTenpoCd', [$tenpo_cd]);

        return parent::setTenpoCd($tenpo_cd);
    }

    /**
     * {@inheritDoc}
     */
    public function getTenpoName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTenpoName', []);

        return parent::getTenpoName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTenpoName(string $tenpo_name): \Customize\Entity\HdnTenpo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTenpoName', [$tenpo_name]);

        return parent::setTenpoName($tenpo_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getTenpoRyakuName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTenpoRyakuName', []);

        return parent::getTenpoRyakuName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTenpoRyakuName(string $tenpo_ryaku_name): \Customize\Entity\HdnTenpo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTenpoRyakuName', [$tenpo_ryaku_name]);

        return parent::setTenpoRyakuName($tenpo_ryaku_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSortNo(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortNo', []);

        return parent::getSortNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSortNo(int $sort_no): \Customize\Entity\HdnTenpo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSortNo', [$sort_no]);

        return parent::setSortNo($sort_no);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', []);

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible(bool $visible): \Customize\Entity\HdnTenpo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phone_number): \Customize\Entity\HdnTenpo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phone_number]);

        return parent::setPhoneNumber($phone_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getUkeTenpo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUkeTenpo', []);

        return parent::getUkeTenpo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUkeTenpo(string $uke_tenpo = NULL): \Customize\Entity\HdnTenpo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUkeTenpo', [$uke_tenpo]);

        return parent::setUkeTenpo($uke_tenpo);
    }

    /**
     * {@inheritDoc}
     */
    public function addSaijiTenpo(\Customize\Entity\HdnSaijiTenpo $saijiTenpo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSaijiTenpo', [$saijiTenpo]);

        return parent::addSaijiTenpo($saijiTenpo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSaijiTenpo(\Customize\Entity\HdnSaijiTenpo $saijiTenpo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSaijiTenpo', [$saijiTenpo]);

        return parent::removeSaijiTenpo($saijiTenpo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSaijiTenpos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaijiTenpos', []);

        return parent::getSaijiTenpos();
    }

}
