<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'eccube.purchase.flow.order.item_preprocessors' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Collection.php';
include_once $this->targetDirs[3].'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemPreprocessor.php';
include_once $this->targetDirs[3].'/app/Customize/Service/PurchaseFlow/Processor/HdnWariItemProcessor.php';

return $this->services['eccube.purchase.flow.order.item_preprocessors'] = new \Doctrine\Common\Collections\ArrayCollection([0 => ${($_ = isset($this->services['Customize\\Service\\PurchaseFlow\\Processor\\HdnWariItemProcessor']) ? $this->services['Customize\\Service\\PurchaseFlow\\Processor\\HdnWariItemProcessor'] : ($this->services['Customize\\Service\\PurchaseFlow\\Processor\\HdnWariItemProcessor'] = new \Customize\Service\PurchaseFlow\Processor\HdnWariItemProcessor())) && false ?: '_'}]);
