<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ProductOption\Repository\OrderItemOptionCategoryRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Repository/OrderItemOptionCategoryRepository.php';

return $this->services['Plugin\\ProductOption\\Repository\\OrderItemOptionCategoryRepository'] = new \Plugin\ProductOption\Repository\OrderItemOptionCategoryRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
