<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Eccube\Form\Type\Admin\OrderStatusSettingType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Eccube/Form/Type/Admin/OrderStatusSettingType.php';

return $this->services['Eccube\\Form\\Type\\Admin\\OrderStatusSettingType'] = new \Eccube\Form\Type\Admin\OrderStatusSettingType(${($_ = isset($this->services['Eccube\\Common\\EccubeConfig']) ? $this->services['Eccube\\Common\\EccubeConfig'] : ($this->services['Eccube\\Common\\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\Master\\OrderStatusColorRepository']) ? $this->services['Eccube\\Repository\\Master\\OrderStatusColorRepository'] : $this->load('getOrderStatusColorRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\\Repository\\Master\\CustomerOrderStatusRepository']) ? $this->services['Eccube\\Repository\\Master\\CustomerOrderStatusRepository'] : $this->load('getCustomerOrderStatusRepositoryService.php')) && false ?: '_'});
