<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ProductOption\Service\PurchaseFlow\Processor\SaleLimitValidator' shared autowired service.

include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ValidatorTrait.php';
include_once $this->targetDirs[3].'/src/Eccube/Service/PurchaseFlow/ItemValidator.php';
include_once $this->targetDirs[3].'/app/Plugin/ProductOption/Service/PurchaseFlow/Processor/SaleLimitValidator.php';

return $this->services['Plugin\\ProductOption\\Service\\PurchaseFlow\\Processor\\SaleLimitValidator'] = new \Plugin\ProductOption\Service\PurchaseFlow\Processor\SaleLimitValidator(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())) && false ?: '_'});
