services:

    # Purchase Flow for Cart
    #    class: Eccube\Service\PurchaseFlow\PurchaseFlow

    eccube.purchase.flow.cart:
        class: Customize\Service\PurchaseFlow\PurchaseFlow
        calls:
            - [setFlowType, ['cart']]
            - [setItemValidators, ['@eccube.purchase.flow.cart.item_validators']]
            - [setItemHolderValidators, ['@eccube.purchase.flow.cart.holder_validators']]
            - [setItemPreprocessors, ['@eccube.purchase.flow.cart.item_preprocessors']]
            - [setItemHolderPreprocessors, ['@eccube.purchase.flow.cart.holder_preprocessors']]
            - [setItemHolderPostValidators, ['@eccube.purchase.flow.cart.holder_post_validators']]

    eccube.purchase.flow.cart.item_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\DeliverySettingValidator' # 配送設定のチェック
                - '@Eccube\Service\PurchaseFlow\Processor\ProductStatusValidator' # 商品の公開状態のチェック
                - '@Eccube\Service\PurchaseFlow\Processor\PriceChangeValidator' # 商品価格の変更検知
                - '@Eccube\Service\PurchaseFlow\Processor\StockValidator' # 在庫のチェック
                - '@Eccube\Service\PurchaseFlow\Processor\SaleLimitValidator' # 販売制限数のチェック

    eccube.purchase.flow.cart.holder_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\EmptyItemsValidator'  # 空明細の削除処理

    eccube.purchase.flow.cart.item_preprocessors:
        class: Doctrine\Common\Collections\ArrayCollection

    eccube.purchase.flow.cart.holder_preprocessors:
        class: Doctrine\Common\Collections\ArrayCollection

    eccube.purchase.flow.cart.holder_post_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentValidator' # 使用できない支払い方法が含まれていないかどうか
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalLimitValidator' # 支払金額の上限チェック
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalNegativeValidator'  # 支払金額のマイナスチェック

    # Purchase Flow for Shopping
    #    class: Eccube\Service\PurchaseFlow\PurchaseFlow
    eccube.purchase.flow.shopping:
        class: Customize\Service\PurchaseFlow\PurchaseFlow
        calls:
            - [setFlowType, ['shopping']]
            - [setItemValidators, ['@eccube.purchase.flow.shopping.item_validators']]
            - [setItemHolderValidators, ['@eccube.purchase.flow.shopping.holder_validators']]
            - [setItemPreprocessors, ['@eccube.purchase.flow.shopping.item_preprocessors']] # (HDN) 割引計算
            - [setItemHolderPreprocessors, ['@eccube.purchase.flow.shopping.holder_preprocessors']]
            - [setDiscountProcessors, ['@eccube.purchase.flow.shopping.discount_processors']]
            - [setItemHolderPostValidators, ['@eccube.purchase.flow.shopping.holder_post_validators']]
            - [setPurchaseProcessors, ['@eccube.purchase.flow.shopping.purchase']]

    eccube.purchase.flow.shopping.item_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\DeliverySettingValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\ProductStatusValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PriceChangeValidator'

    # (HDN) 割引判定を加える
    eccube.purchase.flow.shopping.holder_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\StockMultipleValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\SaleLimitMultipleValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\EmptyItemsValidator'  # 空明細の削除処理
                - '@Customize\Service\PurchaseFlow\Processor\HdnWariOrderProcessor'  # 割引の判定(注文に対して割引判定)

    # (HDN) 割引計算
    eccube.purchase.flow.shopping.item_preprocessors:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Customize\Service\PurchaseFlow\Processor\HdnWariItemProcessor'  # 割引の計算(商品明細に対して割引計算)

    eccube.purchase.flow.shopping.holder_preprocessors:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\TaxProcessor'  # 税額の計算(商品明細に対して税額計算)
                - '@Eccube\Service\PurchaseFlow\Processor\OrderNoProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\TaxProcessor'  # 税額の計算(送料明細・手数料明細に対して税額を計算)

    # 3           - '@Eccube\Service\PurchaseFlow\Processor\DeliveryFeePreprocessor'
    # 4           - '@Eccube\Service\PurchaseFlow\Processor\DeliveryFeeFreeByShippingPreprocessor'
    # 5           - '@Eccube\Service\PurchaseFlow\Processor\PaymentChargePreprocessor'

    eccube.purchase.flow.shopping.discount_processors:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\PointProcessor' # ポイント明細の追加

    eccube.purchase.flow.shopping.holder_post_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\AddPointProcessor'  # 加算ポイントの計算
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalLimitValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalNegativeValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentChargeChangeValidator' # 手数料の変更検知
                - '@Eccube\Service\PurchaseFlow\Processor\DeliveryFeeChangeValidator' # 送料の変更検知

    eccube.purchase.flow.shopping.purchase:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\PreOrderIdValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PointProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\StockReduceProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\CustomerPurchaseInfoProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\OrderUpdateProcessor'

    # Purchase Flow for Order
    #    class: Eccube\Service\PurchaseFlow\PurchaseFlow

    eccube.purchase.flow.order:
        class: Customize\Service\PurchaseFlow\PurchaseFlow
        calls:
            - [setFlowType, ['order']]
            - [setItemValidators, ['@eccube.purchase.flow.order.item_validators']]
            - [setItemHolderValidators, ['@eccube.purchase.flow.order.holder_validators']]
            - [setItemPreprocessors, ['@eccube.purchase.flow.order.item_preprocessors']] # (HDN) 割引計算
            - [setItemHolderPreprocessors, ['@eccube.purchase.flow.order.holder_preprocessors']]
            - [setDiscountProcessors, ['@eccube.purchase.flow.order.discount_processors']]
            - [setItemHolderPostValidators, ['@eccube.purchase.flow.order.holder_post_validators']]
            - [setPurchaseProcessors, ['@eccube.purchase.flow.order.purchase']]

    eccube.purchase.flow.order.item_validators:
        class: Doctrine\Common\Collections\ArrayCollection

    # (HDN) 割引判定を加える
    eccube.purchase.flow.order.holder_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\StockDiffProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\PointDiffProcessor'
                - '@Customize\Service\PurchaseFlow\Processor\HdnWariOrderProcessor'  # 割引の判定(注文に対して割引判定)

    # (HDN) 割引計算
    eccube.purchase.flow.order.item_preprocessors:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Customize\Service\PurchaseFlow\Processor\HdnWariItemProcessor'  # 割引の計算(商品明細に対して割引計算)

    eccube.purchase.flow.order.holder_preprocessors:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\TaxProcessor'

    eccube.purchase.flow.order.discount_processors:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\PointProcessor' # ポイント明細の追加

    eccube.purchase.flow.order.holder_post_validators:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\AddPointProcessor'  # 加算ポイントの計算
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalLimitValidator'
                - '@Eccube\Service\PurchaseFlow\Processor\PaymentTotalNegativeValidator'  # 支払金額のマイナスチェック


    eccube.purchase.flow.order.purchase:
        class: Doctrine\Common\Collections\ArrayCollection
        arguments:
            - #
                - '@Eccube\Service\PurchaseFlow\Processor\StockDiffProcessor'
                - '@Eccube\Service\PurchaseFlow\Processor\PointDiffProcessor'